/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/attendance': typeof AppAttendanceRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/attendance': typeof AppAttendanceRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/attendance'
    | '/app/certificates'
    | '/app/classes'
    | '/app/exams'
    | '/app/notifications'
    | '/app/payments'
    | '/app/reports'
    | '/app/roles'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/attendance'
    | '/app/certificates'
    | '/app/classes'
    | '/app/exams'
    | '/app/notifications'
    | '/app/payments'
    | '/app/reports'
    | '/app/roles'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/attendance'
    | '/app/certificates'
    | '/app/classes'
    | '/app/exams'
    | '/app/notifications'
    | '/app/payments'
    | '/app/reports'
    | '/app/roles'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppClassesRoute: AppClassesRoute,
  AppExamsRoute: AppExamsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
